spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zhn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.bdz.pojo